name: Index Meilisearch Data

on:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  index-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Meilisearch indexing script
        run: node scripts/index_meilisearch.cjs
        env:
          MEILISEARCH_HOST: 'https://search.bettergov.ph' # Or your Meilisearch host
          MEILISEARCH_MASTER_KEY: ${{ secrets.MEILISEARCH_MASTER_KEY }}
